version: "3"
services:
  back_app:
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - "8080:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "mongodatabase"
      
volumes:
  mongodata: 